[package]
name = "runtime-root-upgrade"  # 运行时状态升级与超级管理员模块
edition.workspace = true   # 默认 Rust 版本
version.workspace = true   # 版本号
authors.workspace = true   # 作者
repository.workspace = true  #项目仓库
license = "MIT"        # 授权协议 MIT

[dependencies]
# substrate pallet 相关依赖