[package]
name = "citizennode-backend"  # 统一后端模块
edition.workspace = true   # 默认 Rust 版本
version.workspace = true   # 版本号
authors.workspace = true   # 作者
repository.workspace = true  #项目仓库
license = "MIT"        # 授权协议 MIT

[dependencies]
# 可能依赖 actix-web 或 tokio
